---
apiVersion: v1
kind: Namespace
metadata:
  name: seagull
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    seagull.heavycode.dev/version: "1.14.2"
    seagull.prochowski.dev/type: "github-releases"
    seagull.prochowski.dev/repo: "argoproj/argo-cd"
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80